- hosts: localhost
  connection: local

  # vars:
  #   pip_install_packages:
  #     - php_version: docker

  tasks:
      
    - name: Fetch WordPress Lamp Role
      git:
        repo: https://ro:HyyKcQAjnC28WdDiXEta@pwslab.org/ansible/wordpress-lamp.git
        dest: /root/.ansible/roles/pwslab.wlamp
        version: master
        force: yes

    - name: Check if Apache is already installed
      stat: path=/usr/sbin/httpd
      register: apache_exists

    - name: Check if PHP is already installed
      stat: path=/usr/bin/php
      register: php_exists

    - name: Check if MYSQL is already installed
      stat: path=/usr/bin/mysql
      register: mysql_exists

    - name: Check if version of Ubuntu
      shell: |
        lsb_release -d
      register: ubuntu_os
      ignore_errors: yes

    # - name: Update php Version 
    #   lineinfile:
    #       dest: ~/.ansible/roles/wlemp/templates/nginx.conf.j2
    #       regexp: '^                fastcgi_pass unix:'
    #       line: 'fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;'
    #       state: present
    #   when:
    #     - ubuntu_os.stdout | regex_search("20.04")

    - name: Installing LAMP WORDPRESS
      include_role:
        name: pwslab.wlamp
      when:
        - not apache_exists.stat.exists and not php_exists.stat.exists and not mysql_exists.stat.exists
